#!/bin/bash
echo "Bootstrap Build"

# Stop on first error
set -e

FLAVOR="Release"
SCRIPTS_DIR=$(dirname "$0")

# Build Client
echo $SCRIPTS_DIR/bootstrap-client
$SCRIPTS_DIR/bootstrap-client

# Build SWhere tool
echo $SCRIPTS_DIR/build-swhere $FLAVOR
$SCRIPTS_DIR/build-swhere $FLAVOR

# Build PackageManager
echo $SCRIPTS_DIR/build-packagemanager $FLAVOR
$SCRIPTS_DIR/build-packagemanager $FLAVOR

# Build Tools
echo $SCRIPTS_DIR/bootstrap-tools
$SCRIPTS_DIR/bootstrap-tools

# Build View
echo $SCRIPTS_DIR/build-view $FLAVOR
$SCRIPTS_DIR/build-view $FLAVOR