#!/bin/bash
echo "Build SoupTools!"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")
CODE_DIR=$SCRIPTS_DIR/../../code
TOOLS_DIR=$CODE_DIR/client/tools

# Restore tools
echo soup restore $TOOLS_DIR
soup restore $TOOLS_DIR

# Build tools
echo soup build $TOOLS_DIR -flavor $FLAVOR
soup build $TOOLS_DIR -flavor $FLAVOR