#!/bin/bash
echo "Build Samples: $1"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")

ROOT_DIR=$SCRIPTS_DIR/../..
SAMPLES_DIR=$ROOT_DIR/samples

########################################
## C Samples
########################################

echo soup build $SAMPLES_DIR/c/build-extension/executable/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c/build-extension/executable/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c/console-application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c/console-application/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c/dynamic-library/application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c/dynamic-library/application/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c/static-library/application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c/static-library/application/ -flavor $FLAVOR

echo SKIP: soup build $SAMPLES_DIR/c/windows-application/ -flavor $FLAVOR

########################################
## C# Samples
########################################

echo soup build $SAMPLES_DIR/c#/build-extension/executable/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c#/build-extension/executable/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c#/console-application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c#/console-application/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c#/library/application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c#/library/application/ -flavor $FLAVOR

########################################
## C++ Samples
########################################

echo soup build $SAMPLES_DIR/c++/build-extension/executable/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/build-extension/executable/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c++/console-application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/console-application/ -flavor $FLAVOR

echo SKIP: soup build $SAMPLES_DIR/c++/directx/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c++/dynamic-library/application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/dynamic-library/application/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c++/header-library/application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/header-library/application/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c++/module-dynamic-library/application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/module-dynamic-library/application/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c++/module-interface/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/module-interface/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c++/parse-json/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/parse-json/ -flavor $FLAVOR

echo soup build $SAMPLES_DIR/c++/static-library/application/ -flavor $FLAVOR
eval soup build $SAMPLES_DIR/c++/static-library/application/ -flavor $FLAVOR

echo SKIP: soup build $SAMPLES_DIR/c++/windows-application/ -flavor $FLAVOR