#!/bin/bash
echo "Build Client: $1"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")

ROOT_DIR=$SCRIPTS_DIR/../..
CODE_DIR=$ROOT_DIR/code
OUTPUT_DIR=$ROOT_DIR/out
CLIENT_CLI_DIR=$CODE_DIR/client/cli

# Restore client cli
echo soup restore $CLIENT_CLI_DIR
soup restore $CLIENT_CLI_DIR

# Build client cli
echo soup build $CLIENT_CLI_DIR -flavor $FLAVOR
soup build $CLIENT_CLI_DIR -flavor $FLAVOR

# Restore client native
echo soup restore $CODE_DIR/client/native
soup restore $CODE_DIR/client/native

# Build client native
echo soup build $CODE_DIR/client/native -flavor $FLAVOR
soup build $CODE_DIR/client/native -flavor $FLAVOR