#!/bin/bash
echo "Build: $1"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")

# Build Client
echo $SCRIPTS_DIR/build-client $FLAVOR
eval $SCRIPTS_DIR/build-client $FLAVOR

# Build SWhere tool
echo $SCRIPTS_DIR/build-swhere $FLAVOR
eval $SCRIPTS_DIR/build-swhere $FLAVOR

# Build PackageManager
echo $SCRIPTS_DIR/build-packagemanager $FLAVOR
eval $SCRIPTS_DIR/build-packagemanager $FLAVOR

# Build Tools
echo $SCRIPTS_DIR/build-tools $FLAVOR
eval $SCRIPTS_DIR/build-tools $FLAVOR

# Build View
echo $SCRIPTS_DIR/build-view $FLAVOR
eval $SCRIPTS_DIR/build-view $FLAVOR