#!/bin/bash
echo "Build Soup Tools!"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")
CODE_DIR=$SCRIPTS_DIR/../../code
TOOLS_DIR=$CODE_DIR/tools

# Bootstrap
echo soup restore /bootstrap
soup restore $TOOLS_DIR/bootstrap

echo soup build $TOOLS_DIR/bootstrap -flavor $FLAVOR
soup build $TOOLS_DIR/bootstrap -flavor $FLAVOR

# Copy
echo soup restore $TOOLS_DIR/copy
soup restore $TOOLS_DIR/copy

echo soup build $TOOLS_DIR/copy -flavor $FLAVOR
soup build $TOOLS_DIR/copy -flavor $FLAVOR

# Mkdir
echo soup restore $TOOLS_DIR/mkdir
soup restore $TOOLS_DIR/mkdir

echo soup build $TOOLS_DIR/mkdir -flavor $FLAVOR
soup build $TOOLS_DIR/mkdir -flavor $FLAVOR

# Parse Modules
echo soup restore $TOOLS_DIR/parse-modules
soup restore $TOOLS_DIR/parse-modules

echo soup build $TOOLS_DIR/parse-modules -flavor $FLAVOR
soup build $TOOLS_DIR/parse-modules -flavor $FLAVOR

# Print
echo soup restore $TOOLS_DIR/print
soup restore $TOOLS_DIR/print

echo soup build $TOOLS_DIR/print -flavor $FLAVOR
soup build $TOOLS_DIR/print -flavor $FLAVOR