#!/bin/bash
echo "Build SoupView!"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/../..
CODE_DIR=$ROOT_DIR/code
SWHERE_DIR=$CODE_DIR/generate-sharp/soup-view

# Cleanup old publish to work around bug in publish
rm -r -f $ROOT_DIR/out/msbuild/bin/SoupView/$FLAVOR/net9.0/linux-x64/publish/

# Build SWhere tool
echo dotnet publish $SWHERE_DIR -c $FLAVOR -r linux-x64 --self-contained
dotnet publish $SWHERE_DIR -c $FLAVOR -r linux-x64 --self-contained