#!/bin/bash
echo "Generate SML Lexer!"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/../..
CODE_DIR=$ROOT_DIR/code
CLIENT_CODE_DIR=$CODE_DIR/client/core/source
REFLEX=~/dev/repos/RE-flex/bin/reflex

echo $REFLEX $CLIENT_CODE_DIR/sml/SMLParser.l -o $CLIENT_CODE_DIR/sml/SMLParser.cpp
$REFLEX $CLIENT_CODE_DIR/sml/SMLParser.l -o $CLIENT_CODE_DIR/sml/SMLParser.cpp