#!/bin/bash
echo "Generate Module Parser Lexer!"

# Stop on first error
set -e

FLAVOR="$1"
SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/../..
CODE_DIR=$ROOT_DIR/code
PARSE_MODULES_DIR=$CODE_DIR/parse-modules
REFLEX=~/dev/repos/RE-flex/bin/reflex

echo $REFLEX $PARSE_MODULES_DIR/parser/module-parser.l -o $PARSE_MODULES_DIR/parser/module-parser.cpp
$REFLEX $PARSE_MODULES_DIR/parser/module-parser.l -o $PARSE_MODULES_DIR/parser/module-parser.cpp