#!/bin/bash

# Stop on first error
set -e

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/../..
OUT_DIR=$ROOT_DIR/out
MSBUILD_DIR=$OUT_DIR/msbuild
RUN_DIR=$OUT_DIR/run
BIN_DIR=$RUN_DIR/bin
LIB_DIR=$RUN_DIR/lib/soup

CONFIG_HASH=Oltq7cGwk0Rbgy1I-3mCMDDE5yM

OWNER=mwasplund

SOUP_VERSION="0.43.1"

# Cleanup previous runs
rm -rf $RUN_DIR
mkdir -p $RUN_DIR
mkdir -p $BIN_DIR
mkdir -p $LIB_DIR

cp -p $OUT_DIR/C++/Local/Soup/$SOUP_VERSION/$CONFIG_HASH/bin/Soup.exe $BIN_DIR/soup
cp -p $OUT_DIR/C++/Local/Soup/$SOUP_VERSION/$CONFIG_HASH/bin/Soup.Generate.exe $LIB_DIR/generate

cp -p -R $MSBUILD_DIR/bin/soup.build.package-manager/Release/net10.0/linux-x64/publish/ $LIB_DIR/package-manager

cp -p -R $MSBUILD_DIR/bin/soup-view/Release/net10.0/linux-x64/publish/ $LIB_DIR/view

cp -p -R $MSBUILD_DIR/bin/swhere/Release/net10.0/linux-x64/publish/swhere $BIN_DIR/swhere

$BIN_DIR/soup "$@"