#!/bin/bash

# Stop on first error
set -e

SCRIPTS_DIR=$(dirname "$0")
ROOT_DIR=$SCRIPTS_DIR/../..
OUT_DIR=$ROOT_DIR/out
MSBUILD_DIR=$OUT_DIR/msbuild
RUN_DIR=$OUT_DIR/run
CODE_DIR=$ROOT_DIR/code
GLOBAL_PACKAGES_DIR=~/.soup/packages
GLOBAL_OUT_DIR=~/.soup/out

CONFIG_HASH=OZlIVjblazFuKXg-raWUNoGEnG4

OWNER=mwasplund

SOUP_VERSION="0.42.5"
COPY_VERSION="1.2.0"
MKDIR_VERSION="1.2.0"
PARSE_MODULES_VERSION="1.2.0"
SOUP_WREN_VERSION="0.5.1"

# Cleanup previous runs
rm -rf $RUN_DIR
mkdir -p $RUN_DIR

cp -p $OUT_DIR/C++/Local/Soup/$SOUP_VERSION/$CONFIG_HASH/bin/Soup.exe $RUN_DIR/soup
cp -p $OUT_DIR/C++/Local/Soup/$SOUP_VERSION/$CONFIG_HASH/bin/Soup.Generate.exe $RUN_DIR/generate

mkdir -p $RUN_DIR/BuiltIn/$OWNER/copy/$COPY_VERSION
cp -p $CODE_DIR/tools/copy/recipe.sml $RUN_DIR/BuiltIn/$OWNER/copy/$COPY_VERSION/recipe.sml
cp -p -R $OUT_DIR/C++/Local/copy/$COPY_VERSION/$CONFIG_HASH/ $RUN_DIR/BuiltIn/$OWNER/copy/$COPY_VERSION/out/

mkdir -p $RUN_DIR/BuiltIn/$OWNER/mkdir/$MKDIR_VERSION
cp -p $CODE_DIR/tools/mkdir/recipe.sml $RUN_DIR/BuiltIn/$OWNER/mkdir/$MKDIR_VERSION/recipe.sml
cp -p -R $OUT_DIR/C++/Local/mkdir/$MKDIR_VERSION/$CONFIG_HASH/ $RUN_DIR/BuiltIn/$OWNER/mkdir/$MKDIR_VERSION/out/

mkdir -p $RUN_DIR/BuiltIn/$OWNER/parse.modules/$PARSE_MODULES_VERSION
cp -p $CODE_DIR/tools/parse-modules/recipe.sml $RUN_DIR/BuiltIn/$OWNER/parse.modules/$PARSE_MODULES_VERSION/recipe.sml
cp -p -R $OUT_DIR/C++/Local/parse.modules/$PARSE_MODULES_VERSION/$CONFIG_HASH/ $RUN_DIR/BuiltIn/$OWNER/parse.modules/$PARSE_MODULES_VERSION/out/

mkdir -p $RUN_DIR/BuiltIn/Soup/Wren/$SOUP_WREN_VERSION
cp -p $GLOBAL_PACKAGES_DIR/Wren/Soup/Wren/$SOUP_WREN_VERSION/recipe.sml $RUN_DIR/BuiltIn/Soup/Wren/$SOUP_WREN_VERSION/recipe.sml
cp -p -R $GLOBAL_PACKAGES_DIR/Wren/Soup/Wren/$SOUP_WREN_VERSION/out/$CONFIG_HASH/ $RUN_DIR/BuiltIn/Soup/Wren/$SOUP_WREN_VERSION/out/

cp -p -R $MSBUILD_DIR/bin/soup.build.package-manager/Debug/net9.0/linux-x64/publish/ $RUN_DIR/PackageManager

cp -p -R $MSBUILD_DIR/bin/soup-view/Debug/net9.0/linux-x64/publish/ $RUN_DIR/View

cp -p -R $MSBUILD_DIR/bin/swhere/Debug/net9.0/linux-x64/publish/swhere $RUN_DIR/swhere

$RUN_DIR/soup "$@"