// /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.cpp generated by reflex 5.2.1 from /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l

#define REFLEX_VERSION "5.2.1"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_fast
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_nodefault
#undef REFLEX_OPTION_noline
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_unicode

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           Soup::ParseModules
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_noline              true
#define REFLEX_OPTION_outfile             "/home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.cpp"
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


module;

# include <iostream>
# include <chrono>
# include <optional>
# include <unordered_map>
# include <vector>

export module Soup.ParseModules:ModuleParser;
import reflex;

enum class SimplifiedCppToken : int
{
    EndOfFile = 0,
    Identifier,
    NumberSign,
    LessThan,
    GreaterThan,
    Period,
    Colon,
    Semicolon,
    Module,
    Import,
    Export,
};



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/abslexer.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

} // namespace Soup
} // namespace ParseModules

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {
extern void reflex_code_INITIAL(reflex::Matcher&);
} // namespace Soup
} // namespace ParseModules

int Soup::ParseModules::Lexer::lex(void)
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              lexer_error("scanner jammed");
              return int();
            }
            break;
          case 1: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:40: {whitespace} :
{ /* ignore whitespace */ }
            break;
          case 2: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:41: {preprocessor} :
{ /* ignore preprocessor statements */ }
            break;
          case 3: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:42: {comment} :
{ /* ignore comments */ }
            break;
          case 4: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:43: {newline} :
{ /* ignore newlines */ }
            break;
          case 5: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:44: "import" :
return (int)SimplifiedCppToken::Import;
            break;
          case 6: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:45: "export" :
return (int)SimplifiedCppToken::Export;
            break;
          case 7: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:46: "module" :
return (int)SimplifiedCppToken::Module;
            break;
          case 8: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:47: "#" :
return (int)SimplifiedCppToken::NumberSign;
            break;
          case 9: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:48: "<" :
return (int)SimplifiedCppToken::LessThan;
            break;
          case 10: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:49: ">" :
return (int)SimplifiedCppToken::GreaterThan;
            break;
          case 11: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:50: "." :
return (int)SimplifiedCppToken::Period;
            break;
          case 12: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:51: ":" :
return (int)SimplifiedCppToken::Colon;
            break;
          case 13: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:52: ";" :
return (int)SimplifiedCppToken::Semicolon;
            break;
          case 14: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:53: {identifier} :
return (int)SimplifiedCppToken::Identifier;
            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


namespace Soup::ParseModules
{

/// <summary>
/// Gradient decent Module parser
/// </summary>
export class ModuleParser : public Lexer
{
private:
    SimplifiedCppToken _currentToken;
    std::vector<std::string> _result;

public:
    ModuleParser(const reflex::Input& input) :
        Lexer(input),
        _currentToken(),
        _result()
    {
    }

    bool TryParse()
    {
        MoveNext();

        // Check if there is an optional global module declaration
        if (TryParseOptionalGlobalModuleFragment())
        {
            MoveNext();
        }

        std::string moduleName;
        if (!TryParseModuleDeclaration(moduleName))
            return false;

        _result.push_back("module " + moduleName);

        std::string importName;
        while (TryParseImportModule(importName))
        {
            _result.push_back("import " + importName);
        }

        return true;
    }

    std::vector<std::string> GetResult()
    {
      return std::move(_result);
    }

private:
    bool TryParseOptionalGlobalModuleFragment()
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseOptionalGlobalModuleFragment" << std::endl;
        #endif

        // Verify first token is module
        if (_currentToken != SimplifiedCppToken::Module)
        {
            // There is no global module fragment, return success
            return true;
        }

        // Verify semicolon
        MoveNext();
        if (_currentToken != SimplifiedCppToken::Semicolon)
            return false;

        return true;
    }

    bool TryParseModuleDeclaration(std::string& moduleName)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModuleDeclaration" << std::endl;
        #endif

        // Verify first token is export
        if (_currentToken != SimplifiedCppToken::Export)
            return false;

        // Verify first token is module
        MoveNext();
        if (_currentToken != SimplifiedCppToken::Module)
            return false;

        MoveNext();

        std::string result;
        if (!TryParseModuleName(result))
            return false;

        // Check for optional partition
        std::string partitionName;
        if (TryParseModulePartition(partitionName))
        {
            result += partitionName;
        }

        // Verify semicolon after module name
        if (_currentToken != SimplifiedCppToken::Semicolon)
            return false;

        moduleName = std::move(result);
        return true;
    }

    bool TryParseModuleName(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModuleName" << std::endl;
        #endif

        auto result = std::string();

        // Verify first token is an identifier
        if (_currentToken == SimplifiedCppToken::Identifier)
            result += str();
        else
            return false;

        // Check for optional period separators
        MoveNext();
        while (_currentToken == SimplifiedCppToken::Period)
        {
            result += str();

            // Verify required identifier
            MoveNext();
            if (_currentToken == SimplifiedCppToken::Identifier)
                result += str();
            else
                return false;

            MoveNext();
        }

        name = std::move(result);
        return true;
    }

    bool TryParseModulePartition(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModulePartition" << std::endl;
        #endif

        auto result = std::string(":");

        // Verify first token is a colon
        if (_currentToken != SimplifiedCppToken::Colon)
            return false;

        MoveNext();
        auto moduleName = std::string();
        if (!TryParseModuleName(moduleName))
          return false;

        result += moduleName;
        name = std::move(result);
        return true;
    }

    bool TryParseHeaderName(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseHeaderName" << std::endl;
        #endif

        // TODO: Implement header imports
        name = "TODO";
        return false;
    }

    bool TryParseImportModule(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseImportModule" << std::endl;
        #endif

        // Check for optional first export
        MoveNext();
        if (_currentToken == SimplifiedCppToken::Export)
        {
            // Has Export
            MoveNext();
        }

        // Verify required import
        if (_currentToken != SimplifiedCppToken::Import)
            return false;

        MoveNext();

        auto result = std::string();
        if (TryParseModuleName(result))
        {
            name = std::move(result);
        }
        else if (TryParseModulePartition(result))
        {
            name = std::move(result);
        }
        else if (TryParseHeaderName(result))
        {
            name = std::move(result);
        }
        else
        {
            return false;
        }

        // Verify semicolon at end
        if (_currentToken != SimplifiedCppToken::Semicolon)
            return false;

        return true;
    }

    SimplifiedCppToken MoveNext()
    {
        _currentToken = (SimplifiedCppToken)lex();

        #ifdef SHOW_TOKENS
            switch (_currentToken)
            {
                case SimplifiedCppToken::EndOfFile:
                    std::cout << "Token: " << "EndOfFile" << '\n';
                    break;
                case SimplifiedCppToken::Module:
                    std::cout << "Token: " << "Module" << '\n';
                    break;
                case SimplifiedCppToken::Export:
                    std::cout << "Token: " << "Export" << '\n';
                    break;
                case SimplifiedCppToken::Import:
                    std::cout << "Token: " << "Import" << '\n';
                    break;
                case SimplifiedCppToken::Colon:
                    std::cout << "Token: " << "Colon" << '\n';
                    break;
                case SimplifiedCppToken::Semicolon:
                    std::cout << "Token: " << "Semicolon" << '\n';
                    break;
                case SimplifiedCppToken::Period:
                    std::cout << "Token: " << "Period" << '\n';
                    break;
                case SimplifiedCppToken::Identifier:
                    std::cout << "Token: " << "Identifier" << '\n';
                    break;
                default:
                    std::cout << "Token: " << "UNKNOWN" << '\n';
                    break;
            }
        #endif

        return _currentToken;
    }
};

}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

#if defined(OS_WIN)
#pragma warning(disable:4101 4102)
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-label"
#endif

namespace Soup {
namespace ParseModules {

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c = 0;
  m.FSM_INIT(c);

// S0:
  m.FSM_FIND();
  c = m.FSM_CHAR();
  if (c == 'm') goto S44;
  if (c == 'i') goto S32;
  if (c == 'e') goto S38;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  if (c == '>') goto S52;
  if (c == '<') goto S50;
  if (c == ';') goto S58;
  if (c == ':') goto S56;
  if (c == '/') goto S26;
  if (c == '.') goto S54;
  if (c == '#') goto S22;
  if (c == ' ') goto S18;
  if (c == '\r') goto S28;
  if (c == '\n') goto S30;
  if (c == '\t') goto S18;
  return m.FSM_HALT(c);

S18:
  m.FSM_TAKE(1);
  c = m.FSM_CHAR();
  if (c == ' ') goto S18;
  if (c == '\t') goto S18;
  return m.FSM_HALT(c);

S22:
  m.FSM_TAKE(8);
  c = m.FSM_CHAR();
  if (c == '\r') goto S65;
  if (c == '\n') goto S67;
  if (0 <= c) goto S69;
  return m.FSM_HALT(c);

S26:
  c = m.FSM_CHAR();
  if (c == '/') goto S71;
  return m.FSM_HALT(c);

S28:
  c = m.FSM_CHAR();
  if (c == '\n') goto S30;
  return m.FSM_HALT(c);

S30:
  m.FSM_TAKE(4);
  return m.FSM_HALT();

S32:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'm') goto S74;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S38:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'x') goto S80;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S44:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'o') goto S86;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S50:
  m.FSM_TAKE(9);
  return m.FSM_HALT();

S52:
  m.FSM_TAKE(10);
  return m.FSM_HALT();

S54:
  m.FSM_TAKE(11);
  return m.FSM_HALT();

S56:
  m.FSM_TAKE(12);
  return m.FSM_HALT();

S58:
  m.FSM_TAKE(13);
  return m.FSM_HALT();

S60:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S65:
  c = m.FSM_CHAR();
  if (c == '\n') goto S67;
  if (0 <= c) goto S69;
  return m.FSM_HALT(c);

S67:
  m.FSM_TAKE(2);
  return m.FSM_HALT();

S69:
  c = m.FSM_CHAR();
  if (c == '\n') goto S67;
  if (0 <= c) goto S69;
  return m.FSM_HALT(c);

S71:
  c = m.FSM_CHAR();
  if (c == '\r') goto S92;
  if (c == '\n') goto S94;
  if (0 <= c) goto S96;
  return m.FSM_HALT(c);

S74:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'p') goto S98;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S80:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'p') goto S104;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S86:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'd') goto S110;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S92:
  c = m.FSM_CHAR();
  if (c == '\n') goto S94;
  if (0 <= c) goto S96;
  return m.FSM_HALT(c);

S94:
  m.FSM_TAKE(3);
  return m.FSM_HALT();

S96:
  c = m.FSM_CHAR();
  if (c == '\n') goto S94;
  if (0 <= c) goto S96;
  return m.FSM_HALT(c);

S98:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'o') goto S116;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S104:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'o') goto S122;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S110:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'u') goto S128;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S116:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'r') goto S134;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S122:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'r') goto S140;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S128:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'l') goto S146;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S134:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 't') goto S152;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S140:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 't') goto S157;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S146:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'e') goto S162;
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S152:
  m.FSM_TAKE(5);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S157:
  m.FSM_TAKE(6);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);

S162:
  m.FSM_TAKE(7);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S60;
  if (c == '_') goto S60;
  if ('A' <= c && c <= 'Z') goto S60;
  return m.FSM_HALT(c);
}

} // namespace Soup

} // namespace ParseModules

