// code\tools\parse-module\parser\ModuleParser.cpp generated by reflex 5.5.0 from code\tools\parse-module\parser\ModuleParser.l

#define REFLEX_VERSION "5.5.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_fast
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_nodefault
#undef REFLEX_OPTION_noline
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_unicode

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           Soup::ParseModules
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_noline              true
#define REFLEX_OPTION_outfile             "code\\tools\\parse-module\\parser\\ModuleParser.cpp"
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


module;

# include <iostream>
# include <chrono>
# include <optional>
# include <unordered_map>
# include <vector>

export module Soup.ParseModules:ModuleParser;
import reflex;

enum class SimplifiedCppToken : int
{
    EndOfFile = 0,
    Identifier,
    NumberSign,
    LessThan,
    GreaterThan,
    Period,
    Colon,
    Semicolon,
    Module,
    Import,
    Export,
};



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/abslexer.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

} // namespace Soup
} // namespace ParseModules

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {
extern void reflex_code_INITIAL(reflex::Matcher&);
} // namespace Soup
} // namespace ParseModules

int Soup::ParseModules::Lexer::lex(void)
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              lexer_error("scanner jammed");
              return int();
            }
            break;
          case 1: // rule code\tools\parse-module\parser\ModuleParser.l:40: {whitespace} :
{ /* ignore whitespace */ }
            break;
          case 2: // rule code\tools\parse-module\parser\ModuleParser.l:41: {preprocessor} :
{ /* ignore preprocessor statements */ }
            break;
          case 3: // rule code\tools\parse-module\parser\ModuleParser.l:42: {comment} :
{ /* ignore comments */ }
            break;
          case 4: // rule code\tools\parse-module\parser\ModuleParser.l:43: {newline} :
{ /* ignore newlines */ }
            break;
          case 5: // rule code\tools\parse-module\parser\ModuleParser.l:44: "import" :
return (int)SimplifiedCppToken::Import;
            break;
          case 6: // rule code\tools\parse-module\parser\ModuleParser.l:45: "export" :
return (int)SimplifiedCppToken::Export;
            break;
          case 7: // rule code\tools\parse-module\parser\ModuleParser.l:46: "module" :
return (int)SimplifiedCppToken::Module;
            break;
          case 8: // rule code\tools\parse-module\parser\ModuleParser.l:47: "#" :
return (int)SimplifiedCppToken::NumberSign;
            break;
          case 9: // rule code\tools\parse-module\parser\ModuleParser.l:48: "<" :
return (int)SimplifiedCppToken::LessThan;
            break;
          case 10: // rule code\tools\parse-module\parser\ModuleParser.l:49: ">" :
return (int)SimplifiedCppToken::GreaterThan;
            break;
          case 11: // rule code\tools\parse-module\parser\ModuleParser.l:50: "." :
return (int)SimplifiedCppToken::Period;
            break;
          case 12: // rule code\tools\parse-module\parser\ModuleParser.l:51: ":" :
return (int)SimplifiedCppToken::Colon;
            break;
          case 13: // rule code\tools\parse-module\parser\ModuleParser.l:52: ";" :
return (int)SimplifiedCppToken::Semicolon;
            break;
          case 14: // rule code\tools\parse-module\parser\ModuleParser.l:53: {identifier} :
return (int)SimplifiedCppToken::Identifier;
            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


namespace Soup::ParseModules
{

/// <summary>
/// Gradient decent Module parser
/// </summary>
export class ModuleParser : public Lexer
{
private:
    SimplifiedCppToken _currentToken;
    SimplifiedCppToken _nextToken;
    std::vector<std::string> _result;

public:
    ModuleParser(const reflex::Input& input) :
        Lexer(input),
        _currentToken(),
        _nextToken((SimplifiedCppToken)-1),
        _result()
    {
    }

    bool TryParse()
    {
        MoveNext();

        // Check if there is an optional global module declaration
        if (TryParseOptionalGlobalModuleFragment())
        {
            // TODO: Parse global module fragment

            // Must have a module declaration
            std::string moduleName;
            if (!TryParseModuleDeclaration(moduleName))
                throw std::runtime_error("TU with global module fragment must have a module declaration");

            _result.push_back("module " + moduleName);
        }
        else
        {
            // Check for optional module declarationn
            std::string moduleName;
            if (TryParseModuleDeclaration(moduleName))
            {
                _result.push_back("module " + moduleName);
            }
        }

        std::string importName;
        while (TryParseImportModule(importName))
        {
            _result.push_back("import " + importName);
        }

        return true;
    }

    std::vector<std::string> GetResult()
    {
      return std::move(_result);
    }

private:
    bool TryParseOptionalGlobalModuleFragment()
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseOptionalGlobalModuleFragment" << std::endl;
        #endif

        // Verify first token is module
        if (_currentToken == SimplifiedCppToken::Module &&
          PeekNext() == SimplifiedCppToken::Semicolon)
        {
            // Move past the semicolon
            MoveNext();
            MoveNext();

            // There is a global module fragment
            return true;
        }

        return false;
    }

    bool TryParseModuleDeclaration(std::string& moduleName)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModuleDeclaration" << std::endl;
        #endif

        // Check for optional first export token
        if (_currentToken == SimplifiedCppToken::Export)
        {
            MoveNext();
        }

        // Verify required module token
        if (_currentToken != SimplifiedCppToken::Module)
        {
            // Only return false here since there is not tokens that indicate a module declaration
            return false;
        }

        MoveNext();

        std::string result;
        if (!TryParseModuleName(result))
            throw std::runtime_error("Malformed module name in module declaration");

        // Check for optional partition
        std::string partitionName;
        if (TryParseModulePartition(partitionName))
        {
            result += partitionName;
        }

        // Verify semicolon after module name
        if (_currentToken != SimplifiedCppToken::Semicolon)
            throw std::runtime_error("Malformed module declaration");

        moduleName = std::move(result);
        return true;
    }

    bool TryParseModuleName(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModuleName" << std::endl;
        #endif

        auto result = std::string();

        // Verify first token is an identifier
        if (_currentToken == SimplifiedCppToken::Identifier)
            result += str();
        else
            return false;

        // Check for optional period separators
        MoveNext();
        while (_currentToken == SimplifiedCppToken::Period)
        {
            result += str();

            // Verify required identifier
            MoveNext();
            if (_currentToken == SimplifiedCppToken::Identifier)
                result += str();
            else
                return false;

            MoveNext();
        }

        name = std::move(result);
        return true;
    }

    bool TryParseModulePartition(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseModulePartition" << std::endl;
        #endif

        // Verify first token is a colon
        if (_currentToken != SimplifiedCppToken::Colon)
            return false;

        MoveNext();
        auto moduleName = std::string();
        if (!TryParseModuleName(moduleName))
          return false;

        auto result = std::string(":");
        result += moduleName;
        name = std::move(result);
        return true;
    }

    bool TryParseHeaderName(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseHeaderName" << std::endl;
        #endif

        // TODO: Implement header imports
        name = "TODO";
        return false;
    }

    bool TryParseImportModule(std::string& name)
    {
        #ifdef SHOW_TOKENS
          std::cout << "TryParseImportModule" << std::endl;
        #endif

        // Check for optional first export
        if (_currentToken == SimplifiedCppToken::Export)
        {
            // Has Export
            MoveNext();
        }

        // Verify required import
        if (_currentToken != SimplifiedCppToken::Import)
            return false;

        MoveNext();

        auto result = std::string();
        if (TryParseModuleName(result))
        {
            name = std::move(result);
        }
        else if (TryParseModulePartition(result))
        {
            name = std::move(result);
        }
        else if (TryParseHeaderName(result))
        {
            name = std::move(result);
        }
        else
        {
            return false;
        }

        // Verify semicolon at end
        if (_currentToken != SimplifiedCppToken::Semicolon)
            return false;

        return true;
    }

    SimplifiedCppToken PeekNext()
    {
        if (_nextToken == (SimplifiedCppToken)-1)
        {
            _nextToken = (SimplifiedCppToken)lex();
        }

        return _nextToken;
    }

    SimplifiedCppToken MoveNext()
    {
        if (_nextToken != (SimplifiedCppToken)-1)
        {
            _currentToken = _nextToken;
            _nextToken = (SimplifiedCppToken)-1;
        }
        else
        {
            _currentToken = (SimplifiedCppToken)lex();
        }

        #ifdef SHOW_TOKENS
        switch (_currentToken)
        {
            case SimplifiedCppToken::EndOfFile:
                std::cout << "Token: " << "EndOfFile" << '\n';
                break;
            case SimplifiedCppToken::Module:
                std::cout << "Token: " << "Module" << '\n';
                break;
            case SimplifiedCppToken::Export:
                std::cout << "Token: " << "Export" << '\n';
                break;
            case SimplifiedCppToken::Import:
                std::cout << "Token: " << "Import" << '\n';
                break;
            case SimplifiedCppToken::Colon:
                std::cout << "Token: " << "Colon" << '\n';
                break;
            case SimplifiedCppToken::Semicolon:
                std::cout << "Token: " << "Semicolon" << '\n';
                break;
            case SimplifiedCppToken::Period:
                std::cout << "Token: " << "Period" << '\n';
                break;
            case SimplifiedCppToken::Identifier:
                std::cout << "Token: " << "Identifier" << '\n';
                break;
            default:
                std::cout << "Token: " << "UNKNOWN" << '\n';
                break;
        }
        #endif

        return _currentToken;
    }
};

}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

#if defined(OS_WIN)
#pragma warning(disable:4101 4102)
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-label"
#endif

namespace Soup {
namespace ParseModules {

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c = 0;
  m.FSM_INIT(c);

// S0:
  m.FSM_FIND();
  c = m.FSM_CHAR();
  if (c == 'm') goto S46;
  if (c == 'i') goto S32;
  if (c == 'e') goto S39;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if (c == '>') goto S55;
  if (c == '<') goto S53;
  if (c == ';') goto S61;
  if (c == ':') goto S59;
  if (c == '/') goto S26;
  if (c == '.') goto S57;
  if (c == '#') goto S22;
  if (c == ' ') goto S18;
  if (c == '\r') goto S28;
  if (c == '\n') goto S30;
  if (c == '\t') goto S18;
  return m.FSM_HALT(c);

S18:
  m.FSM_TAKE(1);
  c = m.FSM_CHAR();
  if (c == ' ') goto S18;
  if (c == '\t') goto S18;
  return m.FSM_HALT(c);

S22:
  m.FSM_TAKE(8);
  c = m.FSM_CHAR();
  if (c == '\r') goto S69;
  if (c == '\n') goto S71;
  if (0 <= c) goto S73;
  return m.FSM_HALT(c);

S26:
  c = m.FSM_CHAR();
  if (c == '/') goto S75;
  return m.FSM_HALT(c);

S28:
  c = m.FSM_CHAR();
  if (c == '\n') goto S30;
  return m.FSM_HALT(c);

S30:
  m.FSM_TAKE(4);
  return m.FSM_HALT();

S32:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'm') goto S78;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S39:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'x') goto S85;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S46:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'o') goto S92;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S53:
  m.FSM_TAKE(9);
  return m.FSM_HALT();

S55:
  m.FSM_TAKE(10);
  return m.FSM_HALT();

S57:
  m.FSM_TAKE(11);
  return m.FSM_HALT();

S59:
  m.FSM_TAKE(12);
  return m.FSM_HALT();

S61:
  m.FSM_TAKE(13);
  return m.FSM_HALT();

S63:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S69:
  c = m.FSM_CHAR();
  if (c == '\n') goto S71;
  if (0 <= c) goto S73;
  return m.FSM_HALT(c);

S71:
  m.FSM_TAKE(2);
  return m.FSM_HALT();

S73:
  c = m.FSM_CHAR();
  if (c == '\n') goto S71;
  if (0 <= c) goto S73;
  return m.FSM_HALT(c);

S75:
  c = m.FSM_CHAR();
  if (c == '\r') goto S99;
  if (c == '\n') goto S101;
  if (0 <= c) goto S103;
  return m.FSM_HALT(c);

S78:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'p') goto S105;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S85:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'p') goto S112;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S92:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'd') goto S119;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S99:
  c = m.FSM_CHAR();
  if (c == '\n') goto S101;
  if (0 <= c) goto S103;
  return m.FSM_HALT(c);

S101:
  m.FSM_TAKE(3);
  return m.FSM_HALT();

S103:
  c = m.FSM_CHAR();
  if (c == '\n') goto S101;
  if (0 <= c) goto S103;
  return m.FSM_HALT(c);

S105:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'o') goto S126;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S112:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'o') goto S133;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S119:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'u') goto S140;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S126:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'r') goto S147;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S133:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'r') goto S154;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S140:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'l') goto S161;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S147:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 't') goto S168;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S154:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 't') goto S174;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S161:
  m.FSM_TAKE(14);
  c = m.FSM_CHAR();
  if (c == 'e') goto S180;
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S168:
  m.FSM_TAKE(5);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S174:
  m.FSM_TAKE(6);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);

S180:
  m.FSM_TAKE(7);
  c = m.FSM_CHAR();
  if ('a' <= c && c <= 'z') goto S63;
  if (c == '_') goto S63;
  if ('A' <= c && c <= 'Z') goto S63;
  if ('1' <= c && c <= '9') goto S63;
  return m.FSM_HALT(c);
}

} // namespace Soup

} // namespace ParseModules

