ARG VARIANT=ubuntu26.04
FROM mcr.microsoft.com/devcontainers/base:${VARIANT}
RUN apt-get update

# Install script needed packages.
RUN apt-get upgrade && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install software-properties-common

# Register latest clang
ARG llvm_version=23
RUN wget https://apt.llvm.org/llvm.sh
RUN chmod +x llvm.sh
RUN ./llvm.sh ${llvm_version}

# Install needed packages. Use a separate RUN statement to add your own dependencies.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install build-essential cmake cppcheck valgrind gdb  xdg-utils \
    clang-${llvm_version} \
    clang-format-${llvm_version} \
    clang-tidy-${llvm_version} \
    clangd-${llvm_version} \
    lld-${llvm_version} \
    lldb-${llvm_version} \
    && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install Soup
RUN wget https://github.com/soup-build/soup/releases/latest/download/soup-build-amd64.deb && apt install ./soup-build-amd64.deb && rm soup-build-amd64.deb
RUN swhere
