// /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.cpp generated by reflex 5.2.1 from /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l

#define REFLEX_VERSION "5.2.1"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_fast
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_nodefault
#undef REFLEX_OPTION_noline
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_unicode

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_namespace           Soup::ParseModules
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_noline              true
#define REFLEX_OPTION_outfile             "/home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.cpp"
#define REFLEX_OPTION_unicode             true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


module;

# include <iostream>
# include <chrono>
# include <optional>
# include <unordered_map>
# include <vector>

export module Soup.ParseModules:ModuleParser;
import reflex;

enum class SimplifiedCppToken : int
{
    EndOfFile = 0,
    Newline,
    Colon,
    Semicolon,
    Comma,
    Module,
    Import,
    Export,
    Error,
};



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/abslexer.h>
#endif

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

} // namespace Soup
} // namespace ParseModules

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace Soup {
namespace ParseModules {
extern void reflex_code_INITIAL(reflex::Matcher&);
} // namespace Soup
} // namespace ParseModules

int Soup::ParseModules::Lexer::lex(void)
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              lexer_error("scanner jammed");
              return int();
            }
            break;
          case 1: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:38: {whitespace} :
{ /* ignore whitespace */ }
            break;
          case 2: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:39: {preprocessor} :
{ /* ignore preprocessor statements */ }
            break;
          case 3: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:40: {comment} :
{ /* ignore comments */ }
            break;
          case 4: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:41: {newline} :
return (int)SimplifiedCppToken::Newline;
            break;
          case 5: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:42: "import" :
return (int)SimplifiedCppToken::Import;
            break;
          case 6: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:43: "export" :
return (int)SimplifiedCppToken::Export;
            break;
          case 7: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:44: "module" :
return (int)SimplifiedCppToken::Module;
            break;
          case 8: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:45: ":" :
return (int)SimplifiedCppToken::Colon;
            break;
          case 9: // rule /home/mwasplund/source/repos/soup/scripts/linux/../../code/parse-modules/parser/ModuleParser.l:46: ";" :
return (int)SimplifiedCppToken::Semicolon;
            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////


namespace Soup::ParseModules
{

/// <summary>
/// Gradient decent Module parser
/// </summary>
export class ModuleParser : public Lexer
{
private:
    SimplifiedCppToken _currentToken;

public:
    ModuleParser(const reflex::Input& input) :
        Lexer(input),
        _currentToken()
    {
    }

    bool TryParse()
    {
        std::vector<std::string> imports;
        if (TryParseTranslationUnit(imports))
        {
            // Verify we are at the end of the content
            if (_currentToken != SimplifiedCppToken::EndOfFile)
                return false;

            return true;
        }
        else
        {
            return false;
        }
    }

private:
    bool TryParseTranslationUnit(std::vector<std::string>& imports)
    {
        // Verify first token is module
        MoveNext();
        if (_currentToken != SimplifiedCppToken::Module)
            return false;

        // Verify semicolon
        MoveNext();
        if (_currentToken != SimplifiedCppToken::Semicolon)
            return false;

        return true;
    }

    SimplifiedCppToken MoveNext()
    {
        _currentToken = (SimplifiedCppToken)lex();

        #ifdef SHOW_TOKENS
            switch (_currentToken)
            {
                case SimplifiedCppToken::EndOfFile:
                    std::cout << "Token: " << "EndOfFile" << '\n';
                    break;
                case SimplifiedCppToken::Module:
                    std::cout << "Token: " << "Module" << '\n';
                    break;
                case SimplifiedCppToken::Export:
                    std::cout << "Token: " << "Export" << '\n';
                    break;
                case SimplifiedCppToken::Import:
                    std::cout << "Token: " << "Import" << '\n';
                    break;
                case SimplifiedCppToken::Newline:
                    std::cout << "Token: " << "Newline" << '\n';
                    break;
                case SimplifiedCppToken::Colon:
                    std::cout << "Token: " << "Colon" << '\n';
                    break;
                case SimplifiedCppToken::Semicolon:
                    std::cout << "Token: " << "Semicolon" << '\n';
                    break;
                default:
                    std::cout << "Token: " << "UNKNOWN" << '\n';
                    break;
            }
        #endif

        return _currentToken;
    }
};

}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#ifndef SOUP_BUILD
#include <reflex/matcher.h>
#endif

#if defined(OS_WIN)
#pragma warning(disable:4101 4102)
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-label"
#endif

namespace Soup {
namespace ParseModules {

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c = 0;
  m.FSM_INIT(c);

S0:
  m.FSM_FIND();
  c = m.FSM_CHAR();
  if (c == 'm') goto S29;
  if (c == 'i') goto S25;
  if (c == 'e') goto S27;
  if (c == ';') goto S33;
  if (c == ':') goto S31;
  if (c == '/') goto S19;
  if (c == '#') goto S16;
  if (c == ' ') goto S12;
  if (c == '\r') goto S21;
  if (c == '\n') goto S23;
  if (c == '\t') goto S12;
  return m.FSM_HALT(c);

S12:
  m.FSM_TAKE(1);
  c = m.FSM_CHAR();
  if (c == ' ') goto S12;
  if (c == '\t') goto S12;
  return m.FSM_HALT(c);

S16:
  c = m.FSM_CHAR();
  if (c == '\r') goto S35;
  if (c == '\n') goto S37;
  if (0 <= c) goto S39;
  return m.FSM_HALT(c);

S19:
  c = m.FSM_CHAR();
  if (c == '/') goto S41;
  return m.FSM_HALT(c);

S21:
  c = m.FSM_CHAR();
  if (c == '\n') goto S23;
  return m.FSM_HALT(c);

S23:
  m.FSM_TAKE(4);
  return m.FSM_HALT();

S25:
  c = m.FSM_CHAR();
  if (c == 'm') goto S44;
  return m.FSM_HALT(c);

S27:
  c = m.FSM_CHAR();
  if (c == 'x') goto S46;
  return m.FSM_HALT(c);

S29:
  c = m.FSM_CHAR();
  if (c == 'o') goto S48;
  return m.FSM_HALT(c);

S31:
  m.FSM_TAKE(8);
  return m.FSM_HALT();

S33:
  m.FSM_TAKE(9);
  return m.FSM_HALT();

S35:
  c = m.FSM_CHAR();
  if (c == '\n') goto S37;
  if (0 <= c) goto S39;
  return m.FSM_HALT(c);

S37:
  m.FSM_TAKE(2);
  return m.FSM_HALT();

S39:
  c = m.FSM_CHAR();
  if (c == '\n') goto S37;
  if (0 <= c) goto S39;
  return m.FSM_HALT(c);

S41:
  c = m.FSM_CHAR();
  if (c == '\r') goto S50;
  if (c == '\n') goto S52;
  if (0 <= c) goto S54;
  return m.FSM_HALT(c);

S44:
  c = m.FSM_CHAR();
  if (c == 'p') goto S56;
  return m.FSM_HALT(c);

S46:
  c = m.FSM_CHAR();
  if (c == 'p') goto S58;
  return m.FSM_HALT(c);

S48:
  c = m.FSM_CHAR();
  if (c == 'd') goto S60;
  return m.FSM_HALT(c);

S50:
  c = m.FSM_CHAR();
  if (c == '\n') goto S52;
  if (0 <= c) goto S54;
  return m.FSM_HALT(c);

S52:
  m.FSM_TAKE(3);
  return m.FSM_HALT();

S54:
  c = m.FSM_CHAR();
  if (c == '\n') goto S52;
  if (0 <= c) goto S54;
  return m.FSM_HALT(c);

S56:
  c = m.FSM_CHAR();
  if (c == 'o') goto S62;
  return m.FSM_HALT(c);

S58:
  c = m.FSM_CHAR();
  if (c == 'o') goto S64;
  return m.FSM_HALT(c);

S60:
  c = m.FSM_CHAR();
  if (c == 'u') goto S66;
  return m.FSM_HALT(c);

S62:
  c = m.FSM_CHAR();
  if (c == 'r') goto S68;
  return m.FSM_HALT(c);

S64:
  c = m.FSM_CHAR();
  if (c == 'r') goto S70;
  return m.FSM_HALT(c);

S66:
  c = m.FSM_CHAR();
  if (c == 'l') goto S72;
  return m.FSM_HALT(c);

S68:
  c = m.FSM_CHAR();
  if (c == 't') goto S74;
  return m.FSM_HALT(c);

S70:
  c = m.FSM_CHAR();
  if (c == 't') goto S76;
  return m.FSM_HALT(c);

S72:
  c = m.FSM_CHAR();
  if (c == 'e') goto S78;
  return m.FSM_HALT(c);

S74:
  m.FSM_TAKE(5);
  return m.FSM_HALT();

S76:
  m.FSM_TAKE(6);
  return m.FSM_HALT();

S78:
  m.FSM_TAKE(7);
  return m.FSM_HALT();
}

} // namespace Soup

} // namespace ParseModules

